### ISSUE TITLE
Running Unicorn Payloads on Other Systems

### ISSUE THREAD

**Issue by TecTom2003** [trustedsec/unicorn#103]
I can make a payload easily thanks to your tool, and it runs perfectly on windows and I can even run it over networks. Although I was wondering if there was a way to run it on other operating systems like Macintosh.  If there is, I'd like to know about it and if there isn't, don't crucify me. Thank you!

**Comment by trustedsec** [comment]
No problem and happy to answer - this is a specific attack against Windows-based systems since it involves injecting into memory using Windows-specific language. It's not designed for OS X. Wouldn't be able to use OS X as it's a PowerShell specific attack (Windows-centric, although it's open source now), and the techniques used specifically target Windows platforms. 

Hope that helps!
